const types = {
	FETCH_SUCCEEDED:'FETCH_SUCCEEDED',
	FETCH_POSTS:'FETCH_POSTS',
	RECEIVE_POSTS:'RECEIVE_POSTS',
	ADD_NUMBER:'ADD_NUMBER',
	SUBTRACT_NUMBER:'SUBTRACT_NUMBER',
	FETCH_FAILED: 'FETCH_FAILED',
	FETCH_USERS: 'FETCH_USERS',
	
	// auth types
	SIGN_IN: 'SIGN_IN',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILED: 'SIGN_IN_FAILED',
	SIGN_IN_ERROR: 'SIGN_IN_ERROR',
	SIGN_OUT:'SIGN_OUT',
	
	//error types
	ERRORS: {
		SIGN_IN: 'SIGN_IN',
		GET_ORGANIZATION: 'GET_ORGANIZATION'
	}

	SUCCESS : {
		//ORGANIZATION - 
		GET_ORGANIZATION: 'GET_ORGANIZATION_SUCCESS',
		GET_META_DATA_ORGANIZATION:'GET_META_DATA_ORGANIZATION_SUCCESS',
		GET_ORGANIZATION:'GET_ORGANIZATION_SUCCES',
		//organization - abilities
		GET_ABILITIES: 'GET_ABILITIES_SUCCESS',
		DELETE_ABILITY: 'DELETE_ABILITY_SUCCESS',
		UPDATE_ABILITY:'UPDATE_ABILITY_SUCCESS',
		CREATE_ABILITY: 'CREATE_ABILITY_SUCCESS',
		//organization - basic information
		UPDATE_ORGANIZATION_INFO: 'UPDATE_ORGANIZATION_INFO_SUCCESS',
		//organization - certificate 
		DELETE_CERTIFICATE:'DELETE_CERTIFICATE_SUCCESS',
		UPDATE_CERTIFICATE:'UPDATE_CERTIFICATE_SUCCESS',
		CREATE_CERTIFICATE:'CREATE_CERTIFICATE_SUCCESS',
		//ORGANIZATION - CUSTOMER
		DELETE_CUSTOMER:'DELETE_CUSTOMER_SUCCESS',
		UPDATE_CUSTOMER:'UPDATE_CUSTOMER_SUCCESS',
		CREATE_CUSTOMER:'CREATE_CUSTOMER_SUCCESS',
		//ORGANIZATION - PRODUCTS
		UPDATE_PRODUCT: 'UPDATE_PRODUCT_SUCCESS',
		CREATE_PRODUCT : 'CREATE_PRODUCT_SUCCESS',
		DELETE_PRODUCT : 'DELETE_PRODUCT_SUCCESS',
		DELETE_PICTURE: 'DELETE_PICTURE_SUCCESS',
		ADD_PICTURE : 'ADD_PICTURE_SUCCESS',
	}
	//ORGANIZATION - 
	GET_ORGANIZATION: 'GET_ORGANIZATION',
	GET_META_DATA_ORGANIZATION: 'GET_META_DATA_ORGANIZATION', 
	//organization - abilities
	GET_ABILITIES: 'GET_ABILITIES',
	UPDATE_ABILITY: 'UPDATE_ABILITY',
	CREATE_ABILITY: 'CREATE_ABILITY',
	DELETE_ABILITY: 'DELETE_ABILITY',
	UPDATE_ABILITY_FAILED: 'UPDATE_ABILITY_FAILED',
	CREATE_ABILITY_FAILED: 'CREATE_ABILITY_FAILED',
	DELETE_ABILITY_FAILED: 'DELETE_ABILITY_FAILED',
	//organization - basic information
	UPDATE_ORGANIZATION_INFO: 'UPDATE_ORGANIZATION_INFO',
	UPDATE_ORGANIZATION_INFO_SUCCESS: 'UPDATE_ORGANIZATION_INFO_SUCCESS',
	//organization - certificate 
	UPDATE_CERTIFICATE:'UPDATE_CERTIFICATE',
	CREATE_CERTIFICATE:'CREATE_CERTIFICATE',
	DELETE_CERTIFICATE:'DELETE_CERTIFICATE',
	UPDATE_CERTIFICATE_FAILED:'UPDATE_CERTIFICATE_FAILED',
	CREATE_CERTIFICATE_FAILED:'CREATE_CERTIFICATE_FAILED',
	DELETE_CERTIFICATE_FAILED:'DELETE_CERTIFICATE_FAILED',
	//ORGANIZATION - CUSTOMER
	UPDATE_CUSTOMER:'UPDATE_CUSTOMER',
	CREATE_CUSTOMER:'CREATE_CUSTOMER',
	DELETE_CUSTOMER:'DELETE_CUSTOMER',
	UPDATE_CUSTOMER_FAILED:'UPDATE_CUSTOMER_FAILED',
	CREATE_CUSTOMER_FAILED:'CREATE_CUSTOMER_FAILED',
	DELETE_CUSTOMER_FAILED:'DELETE_CUSTOMER_FAILED',
	//ORGANIZATION - PRODUCTS
	UPDATE_PRODUCT: 'UPDATE_PRODUCT',
	CREATE_PRODUCT : 'CREATE_PRODUCT',
	DELETE_PRODUCT : 'DELETE_PRODUCT',
	ADD_PICTURE : 'ADD_PICTURE',
	DELETE_PICTURE: 'DELETE_PICTURE',
	ADD_PICTURE_SUCCESS : 'ADD_PICTURE_SUCCESS',
	UPDATE_PRODUCT_FAILED: 	'UPDATE_PRODUCT_FAILED',
	CREATE_PRODUCT_FAILED : 'CREATE_PRODUCT_FAILED',
	DELETE_PRODUCT_FAILED : 'DELETE_PRODUCT_FAILED',
}
export default types