const types = {
	FETCH_SUCCEEDED:'FETCH_SUCCEEDED',
	FETCH_POSTS:'FETCH_POSTS',
	RECEIVE_POSTS:'RECEIVE_POSTS',
	ADD_NUMBER:'ADD_NUMBER',
	SUBTRACT_NUMBER:'SUBTRACT_NUMBER',
	FETCH_FAILED: 'FETCH_FAILED',
	FETCH_USERS: 'FETCH_USERS'
}
export default types