export const SUCCESS = '_SUCCESS'
export const FAILED = '_FAILED'
export const REQUEST = '_REQUEST'

const types = {
	FETCH_SUCCEEDED:'FETCH_SUCCEEDED',
	FETCH_POSTS:'FETCH_POSTS',
	RECEIVE_POSTS:'RECEIVE_POSTS',
	ADD_NUMBER:'ADD_NUMBER',
	SUBTRACT_NUMBER:'SUBTRACT_NUMBER',
	FETCH_FAILED: 'FETCH_FAILED',
	FETCH_USERS: 'FETCH_USERS',
	
	// auth types
	SIGN_IN: 'SIGN_IN',
	SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILED: 'SIGN_IN_FAILED',

	// addingProduct
	ADD_CONTRIBUTION: 'ADD_CONTRIBUTION'
}
export default types