export default state => ({
  ...state,
  messages: {
    ...state.messages,
    topBar: {
      ...state.messages.topBar,
      'Home page': 'صفحه اصلی',
      'Explore': 'بگرد',
    },
    "Create New Exchange": "ایجاد پنجرۀ جدید",
    "Exchange Name": "نام پنجره",
    "Exchange Description": "درباره پنجره",
    "Upload Picture": "انتخاب تصویر",
    "Product Video": "ویدیو محصول",
    "Product Gallery": "آلبوم تصاویر محصول",
    "Upload Video": "انتخاب ویدیو",
    'Awesome': 'عالیه!',
    'Congrats, Your Profile Have Been Completed.': 'تبریک، پروفایل شما کامل شد.',
    'View Profile': 'مشاهده پروفایل',
    'Choose a Photo For Profile': 'یک عکس برای پروفایل خود انتخاب کنید.',
    'Not Now': 'فعلا نه',
    'Choose Photo': 'انتخاب عکس',
    'Enter Your Name': 'نام خود را وارد کنید.',
    'Last Education Major': 'آخرین مقطع تحصیلی',
    'Enter Your Last Education Major. You Can Change It Later': 'آخرین مقطع تحصیلی خود را وارد کنید. شما می توانید در ادامه، از داخل صفحه پروفایل مقاطع دیگر را نیز وارد نمایید',
    'Job': 'شغل',
    'Resume Will Introduce a More Professional Profile.': 'سابقه کاری، پروفایل حرفه ای تری از شما معرفی می کند.',
    'Job Title': 'عنوان شغلی',
    'Example: Administration Manager': 'مثال: مدیر اجرایی',
    'Example: Royan Institute': 'مثال: پژوهشکده رویان',
    'Bio': 'بیوگرافی',
    'Write a Short Introduction Of Yourself, Your Activities Or Your Interests': 'معرفی کوتاهی از خود، فعالیت ها یا علاقه مندی هایتان بنویسید.',
    'Example: 23 Years Old | Industrial Designer': 'مثال: 23 ساله | طراح صنعتی',
    'Complement of profile': 'تکمیل پروفایل',
    'Please Enter Bio Text!': 'لطفا متن بیوگرافی را وارد کنید!',
    'Please Enter Name work!': 'لطفا محل کار را وارد کنید!',
    'Please Enter Job Title!': 'لطفا عنوان شغلی را وارد کنید!',
    'Please Select Grade!': 'لطفا مقطع را وارد کنید!',
    'Please Select Major!': 'لطفا رشته را وارد کنید!',
    'Please Select College!': 'لطفا دانشگاه/آموزشگاه را انتخاب کنید!',
    'Please Enter Your Name!': 'لطفا نام خود را وارد نمایید!',
    'Please Enter Your Last Name!': 'لطفا نام خانوادگی خود را وارد نمایید!',
  },
})
