const BASE = {
  GET_OBJECT_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_REQUEST',
  GET_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_REQUEST',
  CREATE_OBJECT_CERTIFICATE: 'COMMON_CREATE_OBJECT_CERTIFICATE_REQUEST',
  RESET_CREATE_CERTIFICATE_STATUS: 'COMMON_RESET_CREATE_CERTIFICATE_STATUS_REQUEST',

  GET_CERTIFICATES_BY_IDENTITY: 'GET_CERTIFICATES_BY_IDENTITY',
  UPDATE_CERTIFICATE: 'UPDATE_CERTIFICATE',
  DELETE_CERTIFICATE: 'DELETE_CERTIFICATE',
}

const SUCCESS = {
  GET_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_SUCCESS',
  GET_OBJECT_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_SUCCESS',
  CREATE_OBJECT_CERTIFICATE: 'COMMON_CREATE_OBJECT_CERTIFICATE_SUCCESS',

  GET_CERTIFICATES_BY_IDENTITY: 'GET_CERTIFICATES_BY_IDENTITY_SUCCESS',
  UPDATE_CERTIFICATE: 'UPDATE_CERTIFICATE_SUCCESS',
  DELETE_CERTIFICATE: 'DELETE_CERTIFICATE_SUCCESS',
}

const ERROR = {
  GET_OBJECT_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_ERROR',
  GET_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_ERROR',
  CREATE_OBJECT_CERTIFICATE: 'COMMON_CREATE_OBJECT_CERTIFICATE_ERROR',

  GET_CERTIFICATES_BY_IDENTITY: 'GET_CERTIFICATES_BY_IDENTITY_ERROR',
  UPDATE_CERTIFICATE: 'UPDATE_CERTIFICATE_ERROR',
  DELETE_CERTIFICATE: 'DELETE_CERTIFICATE_ERROR',
}

export default {
  SUCCESS,
  ERROR,
  BASE
}