const BASE = {
  GET_COMMENTS_BY_PARENT_ID: 'GET_COMMENTS_BY_PARENT_ID',
  CREATE_COMMENT: 'CREATE_COMMENT',
  DELETE_COMMENT: 'DELETE_COMMENT',
}

const SUCCESS = {
  GET_COMMENTS_BY_PARENT_ID: 'GET_COMMENTS_BY_PARENT_ID_SUCCESS',
  CREATE_COMMENT: 'CREATE_COMMENT_SUCCESS',
  DELETE_COMMENT: 'DELETE_COMMENT_SUCCESS',
}

const ERROR = {
  GET_COMMENTS_BY_PARENT_ID: 'GET_COMMENTS_BY_PARENT_ID_ERROR',
  CREATE_COMMENT: 'CREATE_COMMENT_ERROR',
  DELETE_COMMENT: 'DELETE_COMMENT_ERROR',
}

export default {
  SUCCESS,
  ERROR,
  BASE
}