const BASE = {
  GET_COMMENTS_BY_PARENT_ID: 'GET_COMMENTS_BY_PARENT_ID',
}

const SUCCESS = {
  GET_COMMENTS_BY_PARENT_ID: 'GET_COMMENTS_BY_PARENT_ID_SUCCESS',
}

const ERROR = {
  GET_COMMENTS_BY_PARENT_ID: 'GET_COMMENTS_BY_PARENT_ID_ERROR',
}

export default {
  SUCCESS,
  ERROR,
  BASE
}