const BASE = {
  GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY : 'GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY',
  DELETE_EXCHANGE_MEMBERSHIP: 'DELETE_EXCHANGE_MEMBERSHIP',
}

const SUCCESS = {
  GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY : 'GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY_SUCCESS',
  DELETE_EXCHANGE_MEMBERSHIP: 'DELETE_EXCHANGE_MEMBERSHIP_SUCCESS',
}

const ERROR = {
  GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY : 'GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY_ERROR',
  DELETE_EXCHANGE_MEMBERSHIP: 'DELETE_EXCHANGE_MEMBERSHIP_ERROR',
}

export default {
  BASE,
  ERROR,
  SUCCESS,
}
