const BASE = {
  // file
  GET_FILE: 'COMMON_GET_FILE',
  GET_FILES: 'COMMON_GET_FILES_REQUEST',
  CREATE_FILE: 'COMMON_CREATE_FILE_REQUEST',
  UPDATE_FILE: 'COMMON_UPDATE_FILE_REQUEST',
  GET_FILE_BY_RELATED_PARENT_ID: 'COMMON_GET_FILE_BY_RELATED_PARENT_ID_REQUEST',
  DEL_MIDDLEWARE_FILE_DATA: 'COMMON_DELETE_MIDDLEWARE_FILE_DATA_REQUEST',
  // file - temporaryFile
  SET_FILE_IDS_IN_TEMP_FILE:'SET_FILE_IDS_IN_TEMPORARY_FILE',
  REMOVE_FILE_FROM_TEMP_FILE:'REMOVE_FILE_FROM_TEMPORARY_FILE',
}

const SUCCESS = {
  GET_FILE: 'COMMON_GET_FILE_SUCCESS',
  GET_FILES: 'COMMON_GET_FILES_SUCCESS',
  CREATE_FILE: 'COMMON_CREATE_FILE_SUCCESS',
  UPDATE_FILE: 'COMMON_UPDATE_FILE_SUCCESS',
  GET_FILE_BY_RELATED_PARENT_ID: 'COMMON_GET_FILE_BY_RELATED_PARENT_ID_SUCCESS',
}

const ERROR = {
  GET_FILE: 'COMMON_GET_FILE_ERROR',
  GET_FILES: 'COMMON_GET_FILES_ERROR',
  CREATE_FILE: 'COMMON_CREATE_FILE_ERROR',
  UPDATE_FILE: 'COMMON_UPDATE_FILE_ERROR',
  GET_FILE_BY_RELATED_PARENT_ID: 'COMMON_GET_FILE_BY_RELATED_PARENT_ID_ERROR',
}

export default {
  BASE,
  ERROR,
  SUCCESS,
}
