const BASE = {
  GET_FILE: 'COMMON_GET_FILE',
  CREATE_FILE: 'COMMON_CREATE_FILE_REQUEST',
  UPDATE_FILE: 'COMMON_UPDATE_FILE_REQUEST',
  DELETE_FILE: 'COMMON_DELETE_FILE_REQUEST',
  GET_FILE_BY_RELATED_PARENT_ID: 'COMMON_GET_FILE_BY_RELATED_PARENT_ID_REQUEST',
  // file - temporaryFile
  SET_FILE_IDS_IN_TEMP_FILE:'SET_FILE_IDS_IN_TEMPORARY_FILE',
  REMOVE_FILE_FROM_TEMP_FILE:'REMOVE_FILE_FROM_TEMPORARY_FILE',
  SET_FILE_PROGRESS_DETAIL: 'SET_FILE_PROGRESS_DETAIL',
  REMOVE_FILE_PROGRESS_DETAIL: 'REMOVE_FILE_PROGRESS_DETAIL',
}

const SUCCESS = {
  GET_FILE: 'COMMON_GET_FILE_SUCCESS',
  CREATE_FILE: 'COMMON_CREATE_FILE_SUCCESS',
  UPDATE_FILE: 'COMMON_UPDATE_FILE_SUCCESS',
  DELETE_FILE: 'COMMON_DELETE_FILE_SUCCESS',
  GET_FILE_BY_RELATED_PARENT_ID: 'COMMON_GET_FILE_BY_RELATED_PARENT_ID_SUCCESS',
}

const ERROR = {
  GET_FILE: 'COMMON_GET_FILE_ERROR',
  CREATE_FILE: 'COMMON_CREATE_FILE_ERROR',
  UPDATE_FILE: 'COMMON_UPDATE_FILE_ERROR',
  DELETE_FILE: 'COMMON_DELETE_FILE_ERROR',
  GET_FILE_BY_RELATED_PARENT_ID: 'COMMON_GET_FILE_BY_RELATED_PARENT_ID_ERROR',
}

export default {
  BASE,
  ERROR,
  SUCCESS,
}
