const BASE = {
  CREATE_LIKE: 'CREATE_LIKE',
  DELETE_LIKE: 'DELETE_LIKE',
  GET_LIKE_BY_ID: 'GET_LIKE_BY_ID',
}

const SUCCESS = {
  CREATE_LIKE: 'CREATE_LIKE_SUCCESS',
  DELETE_LIKE: 'DELETE_LIKE_SUCCESS',
  GET_LIKE_BY_ID: 'GET_LIKE_BY_ID_SUCCESS',
}

const ERROR = {
  CREATE_LIKE: 'CREATE_LIKE_ERROR',
  DELETE_LIKE: 'DELETE_LIKE_ERROR',
  GET_LIKE_BY_ID: 'GET_LIKE_BY_ID_ERROR',
}

export default {
  SUCCESS,
  ERROR,
  BASE
}