const BASE = {
  GET_MEMBERSHIP_BY_MEMBER_IDENTITY : 'GET_MEMBERSHIP_BY_MEMBER_IDENTITY',
}

const SUCCESS = {
  GET_MEMBERSHIP_BY_MEMBER_IDENTITY : 'GET_MEMBERSHIP_BY_MEMBER_IDENTITY_SUCCESS',
}

const ERROR = {
  GET_MEMBERSHIP_BY_MEMBER_IDENTITY : 'GET_MEMBERSHIP_BY_MEMBER_IDENTITY_ERROR',
}

export default {
  BASE,
  ERROR,
  SUCCESS,
}
