const BASE = {
  GET_PRODUCTS_BY_IDENTITY: 'GET_PRODUCTS_BY_IDENTITY',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  GET_PRODUCT_PRICE: 'GET_PRODUCT_PRICE',
}

const SUCCESS = {
  GET_PRODUCTS_BY_IDENTITY: 'GET_PRODUCTS_BY_IDENTITY_SUCCESS',
  DELETE_PRODUCT: 'DELETE_PRODUCT_SUCCESS',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT_SUCCESS',
  GET_PRODUCT_PRICE: 'GET_PRODUCT_PRICE_SUCCESS',
}

const ERROR = {
  GET_PRODUCTS_BY_IDENTITY: 'GET_PRODUCTS_BY_IDENTITY_ERROR',
  DELETE_PRODUCT: 'DELETE_PRODUCT_ERROR',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT_ERROR',
  GET_PRODUCT_PRICE: 'GET_PRODUCT_PRICE_ERROR',
}

export default {
  SUCCESS,
  ERROR,
  BASE
}