const BASE = {
  GET_PROPOSALS_BY_POST_ID: 'GET_PROPOSALS_BY_POST_ID',
  CREATE_PROPOSAL: 'CREATE_PROPOSAL',
  UPDATE_PROPOSAL: 'UPDATE_PROPOSAL',
}

const SUCCESS = {
  GET_PROPOSALS_BY_POST_ID: 'GET_PROPOSALS_BY_POST_ID_SUCCESS',
  CREATE_PROPOSAL: 'CREATE_PROPOSAL_SUCCESS',
  UPDATE_PROPOSAL: 'UPDATE_PROPOSAL_SUCCESS',
}

const ERROR = {
  GET_PROPOSALS_BY_POST_ID: 'GET_PROPOSALS_BY_POST_ID_ERROR',
  CREATE_PROPOSAL: 'CREATE_PROPOSAL_ERROR',
  UPDATE_PROPOSAL: 'UPDATE_PROPOSAL_ERROR',
}

export default {
  SUCCESS,
  ERROR,
  BASE,
}