const BASE = {
  GET_FOLLOWEES: 'GET_FOLLOWEES',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
  DELETE_FOLLOW: 'DELETE_FOLLOW',
  UPDATE_FOLLOW: 'UPDATE_FOLLOW',
  CREATE_FOLLOW: 'CREATE_FOLLOW',
}

const SUCCESS = {
  GET_FOLLOWEES: 'GET_FOLLOWEES_SUCCESS',
  GET_FOLLOWERS: 'GET_FOLLOWERS_SUCCESS',
  DELETE_FOLLOW: 'DELETE_FOLLOW_SUCCESS',
  UPDATE_FOLLOW: 'UPDATE_FOLLOW_SUCCESS',
  CREATE_FOLLOW: 'CREATE_FOLLOW_SUCCESS',
}

const ERROR = {
  GET_FOLLOWEES: 'GET_FOLLOWEES_ERROR',
  GET_FOLLOWERS: 'GET_FOLLOWERS_ERROR',
  DELETE_FOLLOW: 'DELETE_FOLLOW_ERROR',
  UPDATE_FOLLOW: 'UPDATE_FOLLOW_ERROR',
  CREATE_FOLLOW: 'CREATE_FOLLOW_ERROR',
}


export default {
  BASE,
  ERROR,
  SUCCESS,
}
