const BASE = {
  GET_FOLLOWEES: 'GET_FOLLOWEES',
  GET_FOLLOWERS: 'GET_FOLLOWERS',
  DELETE_FOLLOWERS: 'DELETE_FOLLOWERS',
}

const SUCCESS = {
  GET_FOLLOWEES: 'GET_FOLLOWEES_SUCCESS',
  GET_FOLLOWERS: 'GET_FOLLOWERS_SUCCESS',
  DELETE_FOLLOWERS: 'DELETE_FOLLOWERS_SUCCESS',
}

const ERROR = {
  GET_FOLLOWEES: 'GET_FOLLOWEES_ERROR',
  GET_FOLLOWERS: 'GET_FOLLOWERS_ERROR',
  DELETE_FOLLOWERS: 'DELETE_FOLLOWERS_ERROR',
}


export default {
  BASE,
  ERROR,
  SUCCESS,
}
