const BASE = {
  GET_ABILITIES_BY_ORGANIZATION_ID: 'GET_ABILITIES_BY_ORGANIZATION_ID',
  CREATE_ABILITY: 'CREATE_ABILITY',
  DELETE_ABILITY: 'DELETE_ABILITY',
  UPDATE_ABILITY: 'UPDATE_ABILITY',
}

const SUCCESS = {
  GET_ABILITIES_BY_ORGANIZATION_ID: 'GET_ABILITIES_BY_ORGANIZATION_ID_SUCCESS',
  CREATE_ABILITY: 'CREATE_ABILITY_SUCCESS',
  DELETE_ABILITY: 'DELETE_ABILITY_SUCCESS',
  UPDATE_ABILITY: 'UPDATE_ABILITY_SUCCESS',
}

const ERROR = {
  GET_ABILITIES_BY_ORGANIZATION_ID: 'GET_ABILITIES_BY_ORGANIZATION_ID_ERROR',
  CREATE_ABILITY: 'CREATE_ABILITY_ERROR',
  DELETE_ABILITY: 'DELETE_ABILITY_ERROR',
  UPDATE_ABILITY: 'UPDATE_ABILITY_ERROR',
}


export default {
  BASE,
  ERROR,
  SUCCESS,
}
