const SUCCESS = {
  SIGN_IN: 'SIGN_IN_SUCCESS',
  SET_SELECTED_EXCHANGE: 'SET_SELECTED_EXCHANGE_SUCCESS',
}

const ERROR = {
  SIGN_IN: 'SIGN_IN_ERROR',
  SET_SELECTED_EXCHANGE: 'SET_SELECTED_EXCHANGE_ERROR',
}

const BASE = {
  SET_TOKEN: 'SET_TOKEN',
  SET_SELECTED_EXCHANGE: 'SET_SELECTED_EXCHANGE',
  SIGN_IN: 'SIGN_IN',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_OUT_FINISHED: 'SIGN_OUT_FINISHED',
  VERIFY_TOKEN: 'VERIFY_TOKEN'
}

export default {
  SUCCESS,
  ERROR,
  BASE
}