const SUCCESS = {
    GET_PRODUCT_INFO: 'COMMON_GET_PRODUCT_INFO_SUCCESS',
    UPDATE_PRODUCT: 'COMMON_UPDATE_PRODUCT_SUCCESS',
}

const ERROR = {
    GET_PRODUCT_INFO: 'COMMON_GET_PRODUCT_INFO_ERROR',
    UPDATE_PRODUCT: 'COMMON_UPDATE_PRODUCT_ERROR',
}

const BASE = {
    GET_PRODUCT_INFO: 'COMMON_GET_PRODUCT_INFO',
    UPDATE_PRODUCT: 'COMMON_UPDATE_PRODUCT',
}

export default {
    SUCCESS,
    ERROR,
    BASE
}