const SUCCESS = {
    // product
    GET_PRODUCT_INFO: 'COMMON_GET_PRODUCT_INFO_SUCCESS',
    UPDATE_PRODUCT: 'COMMON_UPDATE_PRODUCT_SUCCESS',

    // category
    GET_CATEGORIES: 'COMMON_GET_CATEGORIES_LIST_SUCCESS',

    // file
    CREATE_FILE: 'COMMON_CREATE_FILE_SUCCESS',
    UPDATE_FILE: 'COMMON_UPDATE_FILE_SUCCESS',

    // certificate
    GET_OBJECT_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_SUCCESS',
    CREATE_OBJECT_CERTIFICATE: 'COMMON_CREATE_OBJECT_CERTIFICATE_SUCCESS'
}

const ERROR = {
    // product
    GET_PRODUCT_INFO: 'COMMON_GET_PRODUCT_INFO_ERROR',
    UPDATE_PRODUCT: 'COMMON_UPDATE_PRODUCT_ERROR',

    // category
    GET_CATEGORIES: 'COMMON_GET_CATEGORIES_LIST_ERROR',

    // file
    CREATE_FILE: 'COMMON_CREATE_FILE_ERROR',
    UPDATE_FILE: 'COMMON_UPDATE_FILE_ERROR',

    // certificate
    GET_OBJECT_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_ERROR',
    CREATE_OBJECT_CERTIFICATE: 'COMMON_CREATE_OBJECT_CERTIFICATE_ERROR'
}

const BASE = {
    // product
    GET_PRODUCT_INFO: 'COMMON_GET_PRODUCT_INFO_REQUEST',
    UPDATE_PRODUCT: 'COMMON_UPDATE_PRODUCT_REQUEST',

    // category
    GET_CATEGORIES: 'COMMON_GET_CATEGORIES_LIST_REQUEST',

    // file
    CREATE_FILE: 'COMMON_CREATE_FILE_REQUEST',
    UPDATE_FILE: 'COMMON_UPDATE_FILE_REQUEST',

    // certificate
    GET_OBJECT_CERTIFICATES: 'COMMON_GET_CERTIFICATE_LIST_BY_PARENT_ID_REQUEST',
    CREATE_OBJECT_CERTIFICATE: 'COMMON_CREATE_OBJECT_CERTIFICATE_REQUEST'
}

export default {
  SUCCESS,
  ERROR,
  BASE
}