const BASE = {
  CREATE_EVENT_ASSIGNMENT: 'CREATE_EVENT_ASSIGNMENT',
}

const SUCCESS = {
  CREATE_EVENT_ASSIGNMENT: 'CREATE_EVENT_ASSIGNMENT_SUCCESS',
}

const ERROR = {
  CREATE_EVENT_ASSIGNMENT: 'CREATE_EVENT_ASSIGNMENT_ERROR',
}


export default {
  BASE,
  ERROR,
  SUCCESS,
}