const BASE = {
	GET_EXCHANGES_BY_MEMBER_IDENTITY: 'GET_EXCHANGES_BY_MEMBER_IDENTITY',
	GET_EXCHANGE_BY_EX_ID: 'GET_EXCHANGE_BY_EX_ID',
	GET_EXCHANGE_MEMBERS_BY_EX_ID: 'GET_EXCHANGE_MEMBERS_BY_EX_ID',
	DELETE_EXCHANGE_MEMBERSHIP: 'DELETE_EXCHANGE_MEMBERSHIP'
}

const SUCCESS = {
	GET_EXCHANGES_BY_MEMBER_IDENTITY: 'GET_EXCHANGES_BY_MEMBER_IDENTITY_SUCCESS',
	GET_EXCHANGE_BY_EX_ID: 'GET_EXCHANGE_SUCCESS',
	GET_EXCHANGE_MEMBERS_BY_EX_ID: 'GET_EXCHANGE_MEMBERS_BY_EX_ID_SUCCESS',
	DELETE_EXCHANGE_MEMBERSHIP: 'DELETE_EXCHANGE_MEMBERSHIP_SUCCESS'
}

const ERROR = {
	GET_EXCHANGE_BY_EX_ID: 'GET_EXCHANGE_ERROR',
	GET_EXCHANGES_BY_MEMBER_IDENTITY: 'GET_EXCHANGES_BY_MEMBER_IDENTITY_ERROR',
	GET_EXCHANGE_MEMBERS_BY_EX_ID: 'GET_EXCHANGE_MEMBERS_BY_EX_ID_ERROR',
	DELETE_EXCHANGE_MEMBERSHIP: 'DELETE_EXCHANGE_MEMBERSHIP_ERROR'
}

const IS_LOADING = {
	GET_EXCHANGES_BY_MEMBER_IDENTITY: 'GET_EXCHANGES_BY_MEMBER_IDENTITY_IS_LOADING'
}

export default {
	BASE,
	ERROR,
	IS_LOADING,
	SUCCESS,
}
