const BASE = {
	GET_EXCHANGE_BY_EX_ID: 'GET_EXCHANGE_BY_EX_ID',
  CREATE_EXCHANGE:'CREATE_EXCHANGE',
}

const SUCCESS = {
	GET_EXCHANGE_BY_EX_ID: 'GET_EXCHANGE_BY_EX_ID_SUCCESS',
	CREATE_EXCHANGE:'CREATE_EXCHANGE_SUCCESS',
}

const ERROR = {
	GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY: 'GET_EXCHANGE_MEMBERSHIP_BY_MEMBER_IDENTITY_ERROR',
	CREATE_EXCHANGE:'CREATE_EXCHANGE_ERROR',
}


export default {
	BASE,
	ERROR,
	SUCCESS,
}
