const ERROR = {
    GET_ORGANIZATION: 'GET_ORGANIZATION_ERROR',
    GET_ORGANIZATION_MEMBERS: 'GET_ORGANIZATION_MEMBERS_ERROR',
    UPDATE_ORGANIZATION_INFO: 'UPDATE_ORGANIZATION_INFO_ERROR',
    GET_USER_IDENTITY: 'GET_ORG_IDENTITY_ERROR',
    GET_ORG_CUSTOMERS: 'GET_ORG_CUSTOMERS_ERROR',
    GET_ORG_CERTIFICATES: 'GET_ORG_CERTIFICATES_ERROR',
    //get products
    GET_PRODUCTS: 'GET_ORG_PRODUCTS_ERROR',
    //socials
    GET_ORG_FOLLOWERS:'GET_ORG_FOLLOWERS_ERROR',
    GET_ORG_FOLLOWINGS: 'GET_ORG_FOLLOWINGS_ERROR',
    GET_ORG_EXCHANGES: 'GET_ORG_EXCHANGES_ERROR',
    GET_ORG_FOLLOWINGS_IDENTITIES: 'GET_ORG_FOLLOWINGS_IDENTITIES_ERROR',
    
    //certificate
    UPDATE_CERTIFICATE: 'UPDATE_ORG_CERTIFICATE_ERROR',
    CREATE_CERTIFICATE: 'CREATE_ORG_CERTIFICATE_ERROR',
    DELETE_CERTIFICATE: 'DELETE_ORG_CERTIFICATE_ERROR',
    
    //customer
    UPDATE_CUSTOMER: 'UPDATE_CUSTOMER_ERROR',
    CREATE_CUSTOMER: 'CREATE_CUSTOMER_ERROR',
    DELETE_CUSTOMER: 'DELETE_CUSTOMER_ERROR',
    CREATE_SKILL: 'CREATE_SKILL_SKILL',
    
    UPDATE_PRODUCT: 'UPDATE_PRODUCT_ERROR', // should move to ERRORS
    CREATE_PRODUCT: 'CREATE_PRODUCT_ERROR', // should move to ERRORS
    DELETE_PRODUCT: 'DELETE_PRODUCT_ERROR', // should move to ERRORS
}

const SUCCESS = {

}

const BASE = {

}


export default {
  SUCCESS,
  ERROR,
  BASE
}