const BASE = {
	FILTER_POSTS_BY_POST_PARENT_LIMIT_OFFSET : 'FILTER_POSTS_BY_POST_PARENT_LIMIT_OFFSET'
}

const SUCCESS = {
	FILTER_POSTS_BY_POST_PARENT_LIMIT_OFFSET : 'FILTER_POSTS_BY_POST_PARENT_LIMIT_OFFSET_SUCCESS'
}

const ERROR = {
	FILTER_POSTS_BY_POST_PARENT_LIMIT_OFFSET : 'FILTER_POSTS_BY_POST_PARENT_LIMIT_OFFSET_ERROR'
}

export default {
	BASE,
	ERROR,
	SUCCESS,
}
