const SUCCESS = {
  CREATE_SKILL: "USER@CREATE_USER_SKILL_SUCCESS"
}

const ERROR = {
  CREATE_SKILL: "USER@CREATE_USER_SKILL_ERROR"
}

const BASE = {
  CREATE_SKILL: "USER@CREATE_USER_SKILL_REQUEST",
  ADD_HASH_TAG_ID_TO_Skill: 'USER@ADD_HASH_TAG_ID_TO_SKILL_REQUEST'
}

export default {
  BASE,
  SUCCESS,
  ERROR
}