const BASE = {
  GET_SKILL_BY_USER_ID: 'GET_SKILL_BY_USER_ID',
  DELETE_SKILL_BY_USER_ID: 'DELETE_SKILL_BY_USER_ID',
  UPDATE_SKILL_BY_USER_ID: 'UPDATE_SKILL_BY_USER_ID',
}

const SUCCESS = {
  GET_SKILL_BY_USER_ID: 'GET_SKILL_BY_USER_ID_SUCCESS',
  DELETE_SKILL_BY_USER_ID: 'DELETE_SKILL_BY_USER_ID_SUCCESS',
  UPDATE_SKILL_BY_USER_ID: 'UPDATE_SKILL_BY_USER_ID_SUCCESS',
}

const ERROR = {
  GET_SKILL_BY_USER_ID: 'GET_SKILL_BY_USER_ID_ERROR',
  DELETE_SKILL_BY_USER_ID: 'DELETE_SKILL_BY_USER_ID_ERROR',
  UPDATE_SKILL_BY_USER_ID: 'UPDATE_SKILL_BY_USER_ID_ERROR',
}


export default {
  BASE,
  ERROR,
  SUCCESS,
}
