const SUCCESS = {
  USERNAME_CHECK:"USERNAME_CHECK",
  CREATE_USER_PERSON:"CREATE_USER_PERSON",
  CREATE_USER_ORGAN:"CREATE_USER_ORGAN"
}

const ERROR = {
  USERNAME_CHECK:"USERNAME_CHECK",
  CREATE_USER_PERSON:"CREATE_USER_PERSON",
  CREATE_USER_ORGAN:"CREATE_USER_ORGAN"
}

const BASE = {
  USERNAME_CHECK:"USERNAME_CHECK",
  CREATE_USER_PERSON:"CREATE_USER_PERSON",
  CREATE_USER_ORGAN:"CREATE_USER_ORGAN"
}


export default {
  SUCCESS,
  ERROR,
  BASE
}