const SUCCESS = {
  USERNAME_CHECK:"USERNAME_CHECK_SUCCESS",
  CREATE_USER_PERSON:"CREATE_USER_PERSON_SUCCESS",
  CREATE_USER_ORGAN:"CREATE_USER_ORGAN_SUCCESS",
  GET_USER_BY_USER_ID:"GET_USER_BY_USER_ID_SUCCESS",
  GET_PROFILE_BY_USER_ID:"GET_PROFILE_BY_USER_ID_SUCCESS",
  GET_USER_IDENTITY:"GET_USER_IDENTITY_SUCCESS",
  UPDATE_USER_BY_USER_ID: "UPDATE_USER_BY_USER_ID_SUCCESS",
  UPDATE_PROFILE_BY_PROFILE_ID: "UPDATE_PROFILE_BY_PROFILE_ID_SUCCESS",
  GET_USERS: "GET_USERS_SUCCESS",
  CREATE_SKILL: "USER@CREATE_USER_SKILL_SUCCESS"
}

const ERROR = {
  USERNAME_CHECK:"USERNAME_CHECK_ERROR",
  CREATE_USER_PERSON:"CREATE_USER_PERSON_ERROR",
  CREATE_USER_ORGAN:"CREATE_USER_ORGAN_ERROR",
  GET_USER_BY_USER_ID:"GET_USER_BY_USER_ID_ERROR",
  GET_PROFILE_BY_USER_ID:"GET_PROFILE_BY_USER_ID_ERROR",
  GET_USER_IDENTITY:"GET_USER_IDENTITY_ERROR",
  UPDATE_USER_BY_USER_ID: "UPDATE_USER_BY_USER_ID_ERROR",
  UPDATE_PROFILE_BY_PROFILE_ID: "UPDATE_PROFILE_BY_PROFILE_ID_ERROR",
  GET_USERS: 'GET_USERS_ERROR',
  CREATE_SKILL: "USER@CREATE_USER_SKILL_ERROR"
}

const BASE = {
  USERNAME_CHECK:"USERNAME_CHECK",
  CREATE_USER_PERSON:"CREATE_USER_PERSON",
  CREATE_USER_ORGAN:"CREATE_USER_ORGAN",
  GET_USER_BY_USER_ID:"GET_USER_BY_USER_ID",
  GET_PROFILE_BY_USER_ID:"GET_PROFILE_BY_USER_ID",
  GET_USER_IDENTITY:"GET_USER_IDENTITY",
  UPDATE_USER_BY_USER_ID: "UPDATE_USER_BY_USER_ID",
  UPDATE_PROFILE_BY_PROFILE_ID: "UPDATE_PROFILE_BY_PROFILE_ID",
  GET_USERS:'GET_USERS',
  CREATE_SKILL: "USER@CREATE_USER_SKILL_REQUEST"
}


export default {
  SUCCESS,
  ERROR,
  BASE
}