const BASE = {
  GET_USER_WORK_EXPERIENCES_BY_USER_ID: 'GET_USER_WORK_EXPERIENCES_BY_USER_ID',
  UPDATE_USER_WORK_EXPERIENCES_BY_USER_ID: 'UPDATE_USER_WORK_EXPERIENCES_BY_USER_ID',
  CREATE_USER_WORK_EXPERIENCES_BY_USER_ID: 'CREATE_USER_WORK_EXPERIENCES_BY_USER_ID',
  DELETE_USER_WORK_EXPERIENCES_BY_USER_ID: 'DELETE_USER_WORK_EXPERIENCES_BY_USER_ID',
}

const SUCCESS = {
  GET_USER_WORK_EXPERIENCES_BY_USER_ID: 'GET_USER_WORK_EXPERIENCES_BY_USER_ID_SUCCESS',
  UPDATE_USER_WORK_EXPERIENCES_BY_USER_ID: 'UPDATE_USER_WORK_EXPERIENCES_BY_USER_ID_SUCCESS',
  CREATE_USER_WORK_EXPERIENCES_BY_USER_ID: 'CREATE_USER_WORK_EXPERIENCES_BY_USER_ID_SUCCESS',
  DELETE_USER_WORK_EXPERIENCES_BY_USER_ID: 'DELETE_USER_WORK_EXPERIENCES_BY_USER_ID_SUCCESS',
}

const ERROR = {
  GET_USER_WORK_EXPERIENCES_BY_USER_ID: 'GET_USER_WORK_EXPERIENCES_BY_USER_ID_ERROR',
  UPDATE_USER_WORK_EXPERIENCES_BY_USER_ID: 'UPDATE_USER_WORK_EXPERIENCES_BY_USER_ID_ERROR',
  CREATE_USER_WORK_EXPERIENCES_BY_USER_ID: 'CREATE_USER_WORK_EXPERIENCES_BY_USER_ID_ERROR',
  DELETE_USER_WORK_EXPERIENCES_BY_USER_ID: 'DELETE_USER_WORK_EXPERIENCES_BY_USER_ID_ERROR',
}

export default {
  SUCCESS,
  ERROR,
  BASE
}