export type postType = {|
  comments : [],
  comments_count: number,
  created_time: string,
  delete_flag: boolean,
  id: number,
  post_description: string,
  post_files_array: [],
  post_related_identity: {
    id: number,
    created_time: string,
    updated_time: string,
    delete_flag: boolean,
    child_name: string,
    name: string,
    accepted: boolean,
    mobile_verified: boolean,
    email_verified: boolean,
    identity_user: {
      id: number,
      password: string,
      last_login: {},
      is_superuser: boolean,
      username: string,
      first_name: string,
      last_name: string,
      email: string,
      is_staff: boolean,
      is_active: boolean,
      date_joined: string,
      groups: [],
      user_permissions: []
    },
    identity_organization: {}
  },
  post_parent: {},
  post_picture: {},
  post_pinned: boolean,
  post_promote: number,
  post_related_product: {},
  post_title: string,
  post_type: string,
  post_user: {
    id: number,
    password: string,
    last_login: {},
    is_superuser: boolean,
    username: string,
    first_name: string,
    last_name: string,
    email: string,
    is_staff: boolean,
    is_active: boolean,
    date_joined: string,
    groups: [],
    user_permissions: []
  },
  updated_time: string,
  post_identity_image: string,
|}