export type shortOrganizationType = {
  id: number,
  owner: {
    id: number,
    username: string,
    first_name: ?string,
    last_name: ?string,
    email: ?string
  },
  admins: [],
  username: string,
  email: string,
  nike_name: ?string,
  official_name: string,
  national_code: ?string,
  meta_data: []
}

export type organizationType = {
  active_flag: boolean,
  address: ?string,
  admins: [],
  biography: ?string,
  business_type: (string)[],
  city: ?string,
  comments_count: number,
  correspondence_language: (string)[],
  country: ?string,
  description: ?string,
  files_count: number,
  email: ?string,
  established_year: ?string,
  id: number,
  meta_data: [],
  national_code: ?string,
  nike_name: ?string,
  official_name: string,
  organization_banner: ?number,
  organization_logo: ?number,
  owner: number,
  ownership_type: string,
  phone: (string)[],
  province: ?string,
  public_email: ?string,
  registrar_organization: ?string,
  registration_ads_url: ?string,
  social_network: (string)[],
  staff_count: ?number,
  username: string,
  web_site: ?string,
}
